### PR TITLE
silly me! This is rdoc!

### PR DESCRIPTION
**Pull request by randym**
Sorry mate - I used md sytax for that! 
Just notices that you are using rdoc.

That's what I get for not checking before hitting PL...

### CODE REVIEW

**Comment by mataki** [comment]
I already fix it!

**Comment by mataki** [comment]
Specs failed...

**Comment by randym** [comment]
you are _fast_

Yeah, looks like a lot of generator specs. I'll clean that up over the next few days

**Comment by mataki** [comment]
Thanks. I forget clean specs up that are genereted.

**Pull request closed without merging**
