### PR TITLE
Github OAuth and automated coderwall login capture - MONSTER PR

### PR DESCRIPTION
**Pull request by randym**
This is a _huge_ PR - sorry about that...

In order to get this running on heroku you will need to set up the application via 
https://github.com/settings/applications/new

And add the key and secret to heroku's env.

When you are in development mode, simply add a oauth_github.yml file to config that contains the following
github_key: [the key generated from the URL above]
github_secret: [the key generated from the URL above]

These values will be automatically loaded in all environments excluding production.
(and ignored via .gitignore)
@see config/initializers/omniauth.rb

Grab me on twitter or freenode #axlsx if you have any questions.

### CODE REVIEW

**Comment by randym** [comment]
btw - you can see a working version of this on:

http://staging-rubygems-leader.herokuapp.com/

Still loading all the users from rubygems, so your account might not be there yet!

And now I've found that there is some email setup to be done as well. Ill hook up sendgrid with a gmail account and see what we see. For now, dont merge this ;0

**Comment by randym** [comment]
Functional version is up on my staging app

http://staging-rubygems-leader.herokuapp.com

I'll see if I can get a profile page added in this weekend as well so people who are showing someone else's coderwall gems can associate their github accounts as well.

**Comment by randym** [comment]
- also - please be sure to contact me before pushing this out to your production heroku app.
  We will need to do a bit of heroku config:add for the sendgrid and github oauth configs for it to work properly.

**Comment by mataki** [comment]
I'm reviewing your pull request.

Why did you use session store?

**Comment by randym** [comment]
Mostly out of habit. Would you rather go with memcached? Or do you know some other swank way to handle sessions that does not involve cookies? Humbly happy to learn!

**Comment by mataki** [comment]
I often use cookie as session store, because rails default.

**Comment by mataki** [comment]
I released your pull request now!
Thanks!!!

**Comment by randym** [comment]
Looks good! I especially like the 'me' button.

regarding sessions, I have always shied away from the default cookie store after reading this:
http://guides.rubyonrails.org/security.html#sessions

Granted we are not currently storing anything overly sensitive at the moment, and are far from the cookie size limit and I still have not implemented any kind of cleanup which leaves us vulnerable to session fixation attacks.

In fact - I think I'll knock that out today.

**Pull request merged**
