### PR TITLE
add coderwall badges to user listing

### PR DESCRIPTION
**Pull request by randym**
Doing something crazy
@mataki What do you think?

### CODE REVIEW

**Comment by mataki** [comment]
Nice!! I like this!

**Comment by mataki** [comment]
but, rubygems.org's handle name always doesn't match github name. like me. 

http://rubygems-leader.herokuapp.com/?utf8=%E2%9C%93&user=mat_aki&commit=Search
http://coderwall.com/mataki

unn...

**Comment by randym** [comment]
hmmm....
OAuth via github and "claim your identities" that sends confirmation email to the address registered with Rubygems ?

**Comment by randym** [comment]
Moved to issue #15

**Pull request merged**
